# Generated by Django 5.1.2 on 2024-11-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('payload', models.TextField(max_length=180)),
            ],
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('tweet', models.ManyToManyField(to='tweets.tweet')),
            ],
            bases=('common.commonmodel',),
        ),
    ]
